export const sampleMarkdown = [
    '# Your next PDF-ready document',
    '',
    'Transform any Markdown note into a polished PDF. This playground renders updates live, lets you inject custom CSS, and exports pixel-perfect PDFs with typographic control.',
    '',
    '## Key features',
    '',
    '- 🎨 Theme presets crafted for editorial, documentation, and night mode workflows.',
    '- 🧱 Drop in custom CSS to match brand guidelines or embed design tokens.',
    '- 🖥️ Resizable, side-by-side editing and rendering panes.',
    '- 📄 Print-ready PDFs powered by Puppeteer\'s typesetting engine under the hood.',
    '',
    '## Markdown essentials',
    '',
    '### Code snippets',
    '',
    '```ts',
    'const iterations = 42;',
    'console.log("Numbers stay aligned thanks to monospaced fonts", iterations);',
    '```',
    '',
    '### Quotes & callouts',
    '',
    '> "Focus on the storytelling. The visuals will follow." — Your future self',
    '',
    '> [!tip]',
    '> Need to share status updates every Friday? Save a template with the preferred CSS and PDF metadata.',
    '',
    '### Tables',
    '',
    '| Sprint | Owner | Status |',
    '| ----- | ----- | ------ |',
    '| 14.1 | Maya | ✅ Done |',
    '| 14.2 | Dani | 🚧 In progress |',
    '| 14.3 | Dev | ⏳ Blocked |',
    '',
    '### Next steps',
    '',
    '1. Drop your Markdown file.',
    '2. Pick a theme or add CSS overrides.',
    '3. Download the PDF and stay confident it will match the design system.'
].join('\n');
